/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Entity.Employee;
import Entity.Employee_Phones;
import company.Tolls;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YOUCEF
 */
public class frmEmployee extends javax.swing.JFrame {

    /**
     * Creates new form frmDepartment
     */
    public frmEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtEmpNO = new controls.JTextBox(15);
        TxtEmpName = new controls.JTextBox(15);
        TxtAddres = new controls.JTextBox(15);
        BtnAdd = new controls.JMyBoutton();
        BtnUpdate = new controls.JMyBoutton();
        BtnFind = new controls.JMyBoutton();
        BtnDelete = new controls.JMyBoutton();
        BtnAll = new controls.JMyBoutton();
        BtnClear = new controls.JMyBoutton();
        BtnBack = new controls.JMyBoutton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblEmp = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        RdoNumber = new javax.swing.JRadioButton();
        RdoName = new javax.swing.JRadioButton();
        RdoAddress = new javax.swing.JRadioButton();
        TxtSearch = new controls.JTextBox(15);
        BtnSearch = new controls.JMyBoutton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtSalary = new controls.JTextBox(15);
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RdoBirth = new javax.swing.JRadioButton();
        RdoHiring = new javax.swing.JRadioButton();
        RdoSalary = new javax.swing.JRadioButton();
        RdoDepartment = new javax.swing.JRadioButton();
        cbxDept = new controls.JMyCombo();
        BtnAddDept = new controls.JMyBoutton();
        jLabel10 = new javax.swing.JLabel();
        TxtPhone = new controls.JTextBox(15);
        BtnAddPhone = new controls.JMyBoutton();
        BtnRemove = new controls.JMyBoutton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TblPhone = new javax.swing.JTable();
        RdoPhone = new javax.swing.JRadioButton();
        TxtHiringDate = new com.toedter.calendar.JDateChooser();
        TxtBirthDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Employee");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Employee NO : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Employee Name : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Employee Address : ");

        TxtEmpNO.setEditable(false);

        TxtAddres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAddresActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnFind.setText("Find");
        BtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFindActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnAll.setText("All");
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });

        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        TblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Address", "Salary", "Hiring Date", "Birth Date", "No", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblEmpMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TblEmp);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Search By :");

        RdoNumber.setBackground(new java.awt.Color(255, 255, 255));
        RdoNumber.setSelected(true);
        RdoNumber.setText("Number");

        RdoName.setBackground(new java.awt.Color(255, 255, 255));
        RdoName.setText("Name");

        RdoAddress.setBackground(new java.awt.Color(255, 255, 255));
        RdoAddress.setText("Address");

        BtnSearch.setText("Search");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Employee Salary : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Employee HiringDate : ");

        TxtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalaryActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Employee BirthDate : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Department NO : ");

        RdoBirth.setBackground(new java.awt.Color(255, 255, 255));
        RdoBirth.setText("Birth ");

        RdoHiring.setBackground(new java.awt.Color(255, 255, 255));
        RdoHiring.setText("Hiring ");

        RdoSalary.setBackground(new java.awt.Color(255, 255, 255));
        RdoSalary.setText("Salary");
        RdoSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoSalaryActionPerformed(evt);
            }
        });

        RdoDepartment.setBackground(new java.awt.Color(255, 255, 255));
        RdoDepartment.setText("Department");
        RdoDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoDepartmentActionPerformed(evt);
            }
        });

        cbxDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDeptActionPerformed(evt);
            }
        });

        BtnAddDept.setText("+");
        BtnAddDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddDeptActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Phone : ");

        TxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPhoneActionPerformed(evt);
            }
        });

        BtnAddPhone.setText("+");
        BtnAddPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddPhoneActionPerformed(evt);
            }
        });

        BtnRemove.setText("Remove");
        BtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveActionPerformed(evt);
            }
        });

        TblPhone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TblPhone);

        RdoPhone.setBackground(new java.awt.Color(255, 255, 255));
        RdoPhone.setText("Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(686, 686, 686))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(51, 51, 51)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbxDept, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(BtnAddDept, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TxtEmpNO)
                                .addComponent(TxtEmpName)
                                .addComponent(TxtAddres)
                                .addComponent(TxtSalary)
                                .addComponent(TxtHiringDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnAddPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(RdoNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoHiring, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RdoName)
                            .addComponent(RdoAddress)
                            .addComponent(RdoSalary)
                            .addComponent(RdoBirth)
                            .addComponent(RdoHiring)
                            .addComponent(RdoDepartment)
                            .addComponent(RdoPhone)
                            .addComponent(RdoNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(TxtEmpNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtAddres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtHiringDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnAddDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(BtnAddPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtAddresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAddresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAddresActionPerformed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        Department dept = new Department();

        emp.getAllRows(TblEmp);

    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        this.dispose();
        Tolls.OpenForm(new frmMain());
    }//GEN-LAST:event_BtnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        BtnGroup.add(RdoHiring);
        BtnGroup.add(RdoDepartment);
        BtnGroup.add(RdoBirth);
        BtnGroup.add(RdoSalary);
        BtnGroup.add(RdoNumber);
        BtnGroup.add(RdoName);
        BtnGroup.add(RdoAddress);
        BtnGroup.add(RdoPhone);
        db.go.fillCombo("department", "DeptNAME", cbxDept);
        emp.getAllRows(TblEmp);
        cleardata();
        TblEmp.getTableHeader().setReorderingAllowed(false);
        TblPhone.getTableHeader().setReorderingAllowed(false);
    }//GEN-LAST:event_formWindowOpened

    Department dept = new Department();
    Employee emp = new Employee();

    private void cleardata() {
        Tolls.ClearText(this);
        TxtEmpNO.setText(emp.getAutoNumber());
        BtnAdd.setEnabled(true);
        BtnUpdate.setEnabled(false);
        BtnDelete.setEnabled(false);
        BtnRemoveActionPerformed(null);
        TxtEmpName.requestFocus();
    }

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        cleardata();

    }//GEN-LAST:event_BtnClearActionPerformed
    private void setValue() {
        emp.setEmpNO(Integer.parseInt(TxtEmpNO.getText()));
        emp.setEmpName(TxtEmpName.getText());
        emp.setSalary(Double.parseDouble(TxtSalary.getText()));
        emp.setAddres(TxtAddres.getText());

        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String HDate = d.format(TxtHiringDate.getDate());
        String BDate = d.format(TxtBirthDate.getDate());
        emp.setBirthDate(BDate);
        emp.setHiringDate(HDate);

        String DName = cbxDept.getSelectedItem().toString();
        String Deptn = dept.getValueByName(DName);
        emp.setDeptNO(Integer.parseInt(Deptn));
    }
    Employee_Phones phones = new Employee_Phones();

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        setValue();
        emp.add();

        //AddPhones
        phones.setEmpNO(Integer.parseInt(TxtEmpNO.getText()));
        for (int x = 0; x < TblPhone.getRowCount(); x++) {
            phones.setPhone(TblPhone.getValueAt(x, 0).toString());
            phones.add();
        }

        cleardata();
        emp.getAllRows(TblEmp);

    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        if (Tolls.confirmMsg("Do You Want To Update ?")) {
            setValue();
            emp.update();

            phones.setEmpNO(Integer.parseInt(TxtEmpNO.getText()));
            //delete phone
            phones.deleteByEmp();
            //add
            for (int x = 0; x < TblPhone.getRowCount(); x++) {
                phones.setPhone(TblPhone.getValueAt(x, 0).toString());
                phones.add();
            }

            cleardata();
            emp.getAllRows(TblEmp);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        if (Tolls.confirmMsg("Do You Want To Delete ?")) {

            phones.setEmpNO(Integer.parseInt(TxtEmpNO.getText()));
            //delete phone
            phones.deleteByEmp();
            setValue();
            emp.delete();
            cleardata();
            emp.getAllRows(TblEmp);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFindActionPerformed
        String stremptNO = (String) Tolls.InputBox("Enter Number Of Emplye");
        emp.setEmpNO(Integer.parseInt(stremptNO));
        emp.getOneRows(TblEmp);


    }//GEN-LAST:event_BtnFindActionPerformed

    private void TblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblEmpMouseClicked
        try {
            int row = TblEmp.getSelectedRow();
            TxtEmpNO.setText(TblEmp.getValueAt(row, 0).toString());
            TxtEmpName.setText(TblEmp.getValueAt(row, 1).toString());
            TxtAddres.setText(TblEmp.getValueAt(row, 2).toString());
            TxtSalary.setText(TblEmp.getValueAt(row, 3).toString());

            SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
            Date HDate = d.parse(TblEmp.getValueAt(row, 4).toString());
            Date BDate = d.parse(TblEmp.getValueAt(row, 5).toString());
            TxtHiringDate.setDate(HDate);
            TxtBirthDate.setDate(BDate);

            cbxDept.setSelectedItem(TblEmp.getValueAt(row, 7));

            phones.setEmpNO(Integer.parseInt(TxtEmpNO.getText()));
            phones.getAllRows(TblPhone);

            BtnAdd.setEnabled(false);
            BtnUpdate.setEnabled(true);
            BtnDelete.setEnabled(true);

        } catch (Exception ex) {
            Tolls.MsgBox(ex.getMessage());
        }
    }//GEN-LAST:event_TblEmpMouseClicked

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        String strSelect = "select * from employee_data where ";
        if (RdoNumber.isSelected()) {
            strSelect += "NUMBER = " + TxtSearch.getText();
            emp.getCustomRows(strSelect, TblEmp);
            cleardata();
        } else if (RdoName.isSelected()) {
            strSelect += "NAME like '%" + TxtSearch.getText() + "%'";
            emp.getCustomRows(strSelect, TblEmp);
            cleardata();
        } else if (RdoAddress.isSelected()) {
            strSelect += "ADDRESS like '%" + TxtSearch.getText() + "%'";
            emp.getCustomRows(strSelect, TblEmp);
            cleardata();
        } else if (RdoSalary.isSelected()) {
            strSelect += "SALARY = " + TxtSearch.getText();
            emp.getCustomRows(strSelect, TblEmp);
            cleardata();
        } else if (RdoHiring.isSelected()) {
            strSelect += "HIRING_DATE like '%" + TxtSearch.getText() + "%'";
            emp.getCustomRows(strSelect, TblEmp);
            cleardata();
        } else if (RdoBirth.isSelected()) {
            strSelect += "BIRTH_OF_DATE like '%" + TxtSearch.getText() + "%'";
            emp.getCustomRows(strSelect, TblEmp);
            cleardata();
        } else if (RdoDepartment.isSelected()) {
            strSelect += "DEPATEMENT like '%" + TxtSearch.getText() + "%' or DEPATEMENT_NO like '%" + TxtSearch.getText() + "%'";
            emp.getCustomRows(strSelect, TblEmp);
            cleardata();
        } else if (RdoPhone.isSelected()){
            String strEmpNum = phones.getEmpNOByPhone(TxtSearch.getText());
            strSelect += "Number like '%" + strEmpNum + "%'";
            emp.getCustomRows(strSelect, TblEmp);
           
            //cleardata();
        }


    }//GEN-LAST:event_BtnSearchActionPerformed

    private void TxtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalaryActionPerformed

    private void RdoSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoSalaryActionPerformed

    private void RdoDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoDepartmentActionPerformed

    private void BtnAddDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddDeptActionPerformed
        int DeptNO = Integer.parseInt(db.go.getAoutoNumber("department", "DeptNO"));
        String DeptNAME = (String) Tolls.InputBox("Enter Name Of Department ");
        String Location = (String) Tolls.InputBox("Enter Location Of " + DeptNAME + " Department ");
        Department dept = new Department();
        dept.setDeptNO(DeptNO);
        dept.setDeptNAME(DeptNAME);
        dept.setLocation(Location);
        dept.add();
        db.go.fillCombo("department", "DeptNAME", cbxDept);
    }//GEN-LAST:event_BtnAddDeptActionPerformed

    private void cbxDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDeptActionPerformed

    private void TxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPhoneActionPerformed

    private void BtnAddPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddPhoneActionPerformed
        DefaultTableModel model = (DefaultTableModel) TblPhone.getModel();
        model.addRow(new Object[]{TxtPhone.getText()});
        TxtPhone.setText("");
        TxtPhone.requestFocus();
    }//GEN-LAST:event_BtnAddPhoneActionPerformed

    private void BtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) TblPhone.getModel();
        model.setNumRows(0);
    }//GEN-LAST:event_BtnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyBoutton BtnAdd;
    private controls.JMyBoutton BtnAddDept;
    private controls.JMyBoutton BtnAddPhone;
    private controls.JMyBoutton BtnAll;
    private controls.JMyBoutton BtnBack;
    private controls.JMyBoutton BtnClear;
    private controls.JMyBoutton BtnDelete;
    private controls.JMyBoutton BtnFind;
    private javax.swing.ButtonGroup BtnGroup;
    private controls.JMyBoutton BtnRemove;
    private controls.JMyBoutton BtnSearch;
    private controls.JMyBoutton BtnUpdate;
    private javax.swing.JRadioButton RdoAddress;
    private javax.swing.JRadioButton RdoBirth;
    private javax.swing.JRadioButton RdoDepartment;
    private javax.swing.JRadioButton RdoHiring;
    private javax.swing.JRadioButton RdoName;
    private javax.swing.JRadioButton RdoNumber;
    private javax.swing.JRadioButton RdoPhone;
    private javax.swing.JRadioButton RdoSalary;
    private javax.swing.JTable TblEmp;
    private javax.swing.JTable TblPhone;
    private javax.swing.JTextField TxtAddres;
    private com.toedter.calendar.JDateChooser TxtBirthDate;
    private javax.swing.JTextField TxtEmpNO;
    private javax.swing.JTextField TxtEmpName;
    private com.toedter.calendar.JDateChooser TxtHiringDate;
    private javax.swing.JTextField TxtPhone;
    private javax.swing.JTextField TxtSalary;
    private javax.swing.JTextField TxtSearch;
    private controls.JMyCombo cbxDept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
