/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Entity.Project;
import company.Tolls;

/**
 *
 * @author YOUCEF
 */
public class frmProject extends javax.swing.JFrame {

    /**
     * Creates new form frmProject
     */
    public frmProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup = new javax.swing.ButtonGroup();
        TxtProjectNAME = new controls.JTextBox(15);
        jLabel5 = new javax.swing.JLabel();
        TxtLocation = new controls.JTextBox(15);
        RdoNumber = new javax.swing.JRadioButton();
        RdoName = new javax.swing.JRadioButton();
        RdoLocation = new javax.swing.JRadioButton();
        TxtSearch = new controls.JTextBox(15);
        BtnSearch = new controls.JMyBoutton();
        BtnAdd = new controls.JMyBoutton();
        BtnUpdate = new controls.JMyBoutton();
        BtnFind = new controls.JMyBoutton();
        BtnDelete = new controls.JMyBoutton();
        jLabel1 = new javax.swing.JLabel();
        BtnAll = new controls.JMyBoutton();
        jLabel2 = new javax.swing.JLabel();
        BtnClear = new controls.JMyBoutton();
        jLabel3 = new javax.swing.JLabel();
        BtnBeak = new controls.JMyBoutton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblProject = new javax.swing.JTable();
        TxtProjectNO = new controls.JTextBox(15);
        BtnAddDept = new controls.JMyBoutton();
        cbxDept = new controls.JMyCombo();
        jLabel9 = new javax.swing.JLabel();
        RdoDept = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1130, 440));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Search By :");

        TxtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLocationActionPerformed(evt);
            }
        });

        RdoNumber.setBackground(new java.awt.Color(255, 255, 255));
        RdoNumber.setSelected(true);
        RdoNumber.setText("Number");

        RdoName.setBackground(new java.awt.Color(255, 255, 255));
        RdoName.setText("Name");

        RdoLocation.setBackground(new java.awt.Color(255, 255, 255));
        RdoLocation.setText("Location");

        BtnSearch.setText("Search");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnFind.setText("Find");
        BtnFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnFindMouseClicked(evt);
            }
        });
        BtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFindActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Project");

        BtnAll.setText("All");
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Project NO : ");

        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Project Name : ");

        BtnBeak.setText("Back");
        BtnBeak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBeakActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Project Location : ");

        TblProject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Location", "NO", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblProjectMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TblProject);

        TxtProjectNO.setEditable(false);

        BtnAddDept.setText("+");
        BtnAddDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddDeptActionPerformed(evt);
            }
        });

        cbxDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDeptActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Department NO : ");

        RdoDept.setBackground(new java.awt.Color(255, 255, 255));
        RdoDept.setText("Department");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtProjectNO)
                                        .addComponent(TxtProjectNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbxDept, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnAddDept, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(BtnBeak, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(RdoNumber)
                                .addGap(17, 17, 17)
                                .addComponent(RdoName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RdoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RdoDept, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(513, 513, 513)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(RdoNumber)
                    .addComponent(RdoName)
                    .addComponent(RdoLocation)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdoDept))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TxtProjectNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtProjectNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAddDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(55, 55, 55)
                        .addComponent(BtnBeak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLocationActionPerformed

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed

        String strserch = "select * from project_data where ";

        if (RdoNumber.isSelected()) {
            strserch += "NUMBER =" + TxtSearch.getText();
            db.go.fillToJTable(strserch, TblProject);
            
        } else if (RdoName.isSelected()) {
            strserch += "NAME like '%" + TxtSearch.getText() + "%'";
            db.go.fillToJTable(strserch, TblProject);
        } else if (RdoLocation.isSelected()) {
            strserch += "LOCATION like '%" + TxtSearch.getText() + "%'";
            db.go.fillToJTable(strserch, TblProject);
        } else if (RdoDept.isSelected()) {
            strserch += "DEPARTMENT_NAME like '%" + TxtSearch.getText() + "%'"
                    +"or DEPARTMENT_NUMBER = " +TxtSearch.getText();
            db.go.fillToJTable(strserch, TblProject);
        }
        cleardata();

    }//GEN-LAST:event_BtnSearchActionPerformed
    Project proj = new Project();

    private void setValue() {
        proj.setProjectNO(Integer.parseInt(TxtProjectNO.getText()));
        proj.setProjectName(TxtProjectNAME.getText());
        proj.setLocation(TxtLocation.getText());
        proj.setDeptNO(Integer.parseInt(dept.getValueByName(cbxDept.getSelectedItem().toString())));
    }
    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        setValue();
        proj.add();
        cleardata();
        proj.getAllRows(TblProject);
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        if (Tolls.confirmMsg("Do You Want To Update ?")) {
            setValue();
            proj.update();
            cleardata();
            proj.getAllRows(TblProject);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFindActionPerformed
        int StrProjNO = Integer.parseInt(Tolls.InputBox("Enter Project Number").toString());
        String strSelect = "select * from project_data where number = " + StrProjNO;
        db.go.fillToJTable(strSelect, TblProject);
        cleardata();

    }//GEN-LAST:event_BtnFindActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        if (Tolls.confirmMsg("Do You Want To Delete ?")) {
            setValue();
            proj.delete();
            cleardata();
            proj.getAllRows(TblProject);

        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        db.go.fillToJTable("Project_data", TblProject);
    }//GEN-LAST:event_BtnAllActionPerformed
    private void cleardata() {
        Tolls.ClearText(this);
        TxtProjectNO.setText(proj.getAutoNumber());
        TxtProjectNO.requestFocus();
        BtnDelete.setEnabled(false);
        BtnUpdate.setEnabled(false);
        BtnAdd.setEnabled(true);

    }
    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        cleardata();

    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnBeakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBeakActionPerformed
        this.dispose();
        Tolls.OpenForm(new frmMain());
    }//GEN-LAST:event_BtnBeakActionPerformed

    private void TblProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblProjectMouseClicked
        try {
            int row = TblProject.getSelectedRow();

            String ProjNO = TblProject.getValueAt(row, 0).toString();
            String ProjName = TblProject.getValueAt(row, 1).toString();
            String Location = TblProject.getValueAt(row, 2).toString();
            String DeptName = TblProject.getValueAt(row, 4).toString();

            TxtProjectNO.setText(ProjNO);
            TxtProjectNAME.setText(ProjName);
            TxtLocation.setText(Location);
            cbxDept.setSelectedItem(DeptName);
            BtnAdd.setEnabled(false);
            BtnDelete.setEnabled(true);
            BtnUpdate.setEnabled(true);

        } catch (Exception ex) {
            Tolls.MsgBox(ex.getMessage());
        }
    }//GEN-LAST:event_TblProjectMouseClicked
    Department dept = new Department();
    private void BtnAddDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddDeptActionPerformed
        int DeptNO = Integer.parseInt(dept.getAutoNumber());
        String DeptName = Tolls.InputBox("Enter Department Name").toString();
        String Location = Tolls.InputBox("Enter Department Location").toString();
        dept.setDeptNAME(DeptName);
        dept.setDeptNO(DeptNO);
        dept.setLocation(Location);
        dept.add();

        db.go.fillCombo("department", "DeptName", cbxDept);
    }//GEN-LAST:event_BtnAddDeptActionPerformed

    private void cbxDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDeptActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TblProject.getTableHeader().setReorderingAllowed(false);
        BtnGroup.add(RdoLocation);
        BtnGroup.add(RdoName);
        BtnGroup.add(RdoDept);
        BtnGroup.add(RdoNumber);
        db.go.fillCombo("department", "DeptNAME", cbxDept);
        proj.getAllRows(TblProject);
        cleardata();
    }//GEN-LAST:event_formWindowOpened

    private void BtnFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFindMouseClicked

    }//GEN-LAST:event_BtnFindMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyBoutton BtnAdd;
    private controls.JMyBoutton BtnAddDept;
    private controls.JMyBoutton BtnAll;
    private controls.JMyBoutton BtnBeak;
    private controls.JMyBoutton BtnClear;
    private controls.JMyBoutton BtnDelete;
    private controls.JMyBoutton BtnFind;
    private javax.swing.ButtonGroup BtnGroup;
    private controls.JMyBoutton BtnSearch;
    private controls.JMyBoutton BtnUpdate;
    private javax.swing.JRadioButton RdoDept;
    private javax.swing.JRadioButton RdoLocation;
    private javax.swing.JRadioButton RdoName;
    private javax.swing.JRadioButton RdoNumber;
    private javax.swing.JTable TblProject;
    private javax.swing.JTextField TxtLocation;
    private javax.swing.JTextField TxtProjectNAME;
    private javax.swing.JTextField TxtProjectNO;
    private javax.swing.JTextField TxtSearch;
    private controls.JMyCombo cbxDept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
