/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Entity.Employee;
import Entity.Employee_Phones;
import Entity.Project;
import Entity.Workon;
import static com.sun.javafx.scene.CameraHelper.project;
import company.Tolls;
import jdk.nashorn.internal.ir.EmptyNode;

/**
 *
 * @author YOUCEF
 */
public class frmTest extends javax.swing.JFrame {

    /**
     * Creates new form frmTest
     */
    public frmTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jMyBoutton1 = new controls.JMyBoutton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jMyBoutton2 = new controls.JMyBoutton();
        BtnPhones = new controls.JMyBoutton();
        jMyBoutton3 = new controls.JMyBoutton();
        BtnTestWorkon = new controls.JMyBoutton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMyBoutton1.setText("Test department");
        jMyBoutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBoutton1ActionPerformed(evt);
            }
        });

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMyBoutton2.setText("Test Employee");
        jMyBoutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBoutton2ActionPerformed(evt);
            }
        });

        BtnPhones.setText("Test Phones");
        BtnPhones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPhonesActionPerformed(evt);
            }
        });

        jMyBoutton3.setText("Test Project");
        jMyBoutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBoutton3ActionPerformed(evt);
            }
        });

        BtnTestWorkon.setText("Test Workon");
        BtnTestWorkon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTestWorkonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jMyBoutton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMyBoutton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnPhones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMyBoutton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTestWorkon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(145, 145, 145)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jMyBoutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMyBoutton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnPhones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMyBoutton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnTestWorkon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMyBoutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBoutton1ActionPerformed
    Department dept = new Department();
    //dept.setDeptNO(1);
    //dept.setDeptNAME("gabi4");
    //dept.setLocation("warsaw4");
    //dept.add();
    //dept.delete();
    //dept.update();
    dept.getAllRows(jt);
    //dept.getOneRows(jTable1);
    //Tolls.MsgBox(dept.getAutoNumber());
    //dept.getCustomRows("select * from department where deptno=1", jTable1);
   //Tolls.MsgBox(dept.getValueByName("gabi22"));
   //Tolls.MsgBox(dept.getNameByValue("2"));
    
    }//GEN-LAST:event_jMyBoutton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Tolls.confirmMsg("Do you love me ?" );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMyBoutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBoutton2ActionPerformed
        Employee emp = new Employee();
        emp.setEmpNO(1);
        emp.setEmpName("vv hedjerci");
        emp.setAddres("algeria");
        emp.setSalary(9080.0);
        emp.setHiringDate("2017-05-01");
        emp.setBirthDate("2011-03-08");
        emp.setDeptNO(2);
        //emp.add();
        //emp.update();
        //emp.delete();
        //emp.getAllRows(jt);
        //Tolls.MsgBox(emp.getAutoNumber());
       // emp.getCustomRows("select * from employee", jt);
        //Tolls.MsgBox(emp.getValueByName("youcef hedjerci"));
        //Tolls.MsgBox(emp.getNameByValue("1"));
        emp.getOneRows(jt);
    }//GEN-LAST:event_jMyBoutton2ActionPerformed

    private void BtnPhonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPhonesActionPerformed
         Employee_Phones phones = new Employee_Phones();
         phones.setEmpNO(2);
         //phones.setPhone("+213729807306");
         //phones.setPhone("0771046436");
         //phones.setPhone("0779996381");
         //phones.add(); 
         //phones.delete();
         //phones.deleteByEmp();
         phones.getAllRows(jt);
    }//GEN-LAST:event_BtnPhonesActionPerformed
        Project proj = new Project();
        
        
    private void jMyBoutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBoutton3ActionPerformed
        proj.setDeptNO(4);
        proj.setLocation("war0s++");
        proj.setProjectName("4bing+++");
        proj.setProjectNO(3);
        //proj.add();
        //proj.delete();
        //proj.update();
        //Tolls.MsgBox(proj.getAutoNumber());
        //proj.getAllRows(jt);
        //proj.getOneRows(jt);
        //proj.getCustomRows("select * from project_data where number=1", jt);
        //Tolls.MsgBox(proj.getValueByName("buiding++"));
        //Tolls.MsgBox(proj.getNameByValue("1"));
    }//GEN-LAST:event_jMyBoutton3ActionPerformed
        Workon work = new Workon();
    private void BtnTestWorkonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTestWorkonActionPerformed
        work.setEmpNO(4);
        work.setProjectNO(4);
        //work.add();
        //work.delete();
        //work.getAllRows(jt);
        //work.getOneRows(jt);
        work.getCustomRows("select * from workon_data", jt);
    }//GEN-LAST:event_BtnTestWorkonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyBoutton BtnPhones;
    private controls.JMyBoutton BtnTestWorkon;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private controls.JMyBoutton jMyBoutton1;
    private controls.JMyBoutton jMyBoutton2;
    private controls.JMyBoutton jMyBoutton3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jt;
    // End of variables declaration//GEN-END:variables
}
